[project]
name = "Weather Station"

[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"

[dependencies]
arduinojson = "*"
liquidcrystal_i2c = "*"

[components]
esp32 = { type = "ESP32", id = "esp32" }
lcd = { type = "LiquidCrystal_I2C", id = "lcd", address = 0x27 }
wire1 = { type = "Wire", from = "esp32:21", to = "lcd:SDA" }
wire2 = { type = "Wire", from = "esp32:22", to = "lcd:SCL" }
power1 = { type = "Power", from = "esp32:3V3", to = "lcd:VCC" }
ground1 = { type = "Ground", from = "esp32:GND", to = "lcd:GND" }
